# Cargo deny configuration for security analysis
# This file controls what cargo-deny will check for

[advisories]
# Security vulnerabilities
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    # Add specific advisories to ignore here if needed
    # "RUSTSEC-2020-0001",
]

[licenses]
# License restrictions
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
# Banned dependencies
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
    # Add specific multiple version exceptions here
]
deny = [
    # Ban specific problematic crates
    { name = "openssl", version = "*" },  # Prefer rustls
    { name = "native-tls", version = "*" },  # Prefer rustls
]
skip = [
    # Skip checking these dependencies
]
skip-tree = [
    # Skip entire dependency trees
]

[sources]
# Allowed sources for dependencies
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/renegade-fi/ark-mpc",
    "https://github.com/renegade-fi/mpc-jellyfish.git",
    "https://github.com/tkaitchuck/aHash.git",
]
